-- SupplyHUB schema — mirrors lib/types.ts 1:1 so no app shape changes are needed.
-- Note: uses GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so the migration script
-- can insert rows with explicit IDs preserved from the old JSON store.
-- RLS is intentionally disabled in Step 1; all access is server-side via service-role key.
-- Step 2 (auth) will enable RLS and switch reads to the per-user anon client.

create table if not exists clients (
  id      bigint generated by default as identity primary key,
  name    text   not null,
  contact text,
  email   text,
  phone   text
);

create table if not exists partners (
  id                   bigint  generated by default as identity primary key,
  company              text    not null,
  contact              text,
  email                text,
  phone                text,
  categories           text,
  rating               numeric default 0,
  active               int     default 1,
  location             text,
  preferred_channels   text,
  avg_delivery_days    int,
  website              text,
  logo_path            text,
  bank_name            text,
  bank_account         text,
  portal_contact_name  text,
  portal_email         text,
  -- Stays JSONB for now (array of {name, moq, delivery_days, price, currency}).
  -- Normalise into a child table in a later ticket if needed.
  products             jsonb   default '[]'::jsonb,
  created_at           text
);

create table if not exists orders (
  id           bigint generated by default as identity primary key,
  client_id    bigint references clients(id),
  order_number text,
  notes        text,
  created_at   text
);

create table if not exists product_requests (
  id            bigint generated by default as identity primary key,
  order_id      bigint references orders(id),
  title         text not null,
  category      text,
  specs         text,
  quantity      int,
  needed_by     text,
  hide_client   int  default 1,
  status        text default 'draft',
  created_at    text,
  standard_size text,
  width         numeric,
  height        numeric,
  size_unit     text,
  material      text,
  finishing     text,
  attachments   text
);

create table if not exists dispatches (
  id          bigint generated by default as identity primary key,
  request_id  bigint references product_requests(id),
  partner_id  bigint references partners(id),
  sent_at     text,
  unique (request_id, partner_id)
);

create table if not exists quotes (
  id             bigint  generated by default as identity primary key,
  dispatch_id    bigint  references dispatches(id),
  price          numeric,
  currency       text    default 'USD',
  lead_time_days int,
  valid_until    text,
  conditions     text,
  status         text    default 'submitted',
  revision       int     default 1,
  created_at     text
);

create table if not exists messages (
  id          bigint generated by default as identity primary key,
  request_id  bigint references product_requests(id),
  partner_id  bigint references partners(id),
  author_role text,
  text        text,
  created_at  text
);
