-- Single-row company settings table (id is always 1).
-- Stores the print house's own company info, shown to vendors as contact info.
create table if not exists company_settings (
  id               bigint generated by default as identity primary key,
  company_name     text,
  logo_path        text,
  hq_address       text,
  branches         text,          -- newline-separated list of branch addresses
  ci_number        text,          -- company registration / CI number
  ein              text,          -- employer identification / tax number
  bank_name        text,
  bank_account     text,
  swift            text,
  payment_terms    text,
  manager_name     text,          -- distribution manager full name
  manager_phone    text,
  manager_email    text,
  contact_name     text,          -- contact info shown to vendors/partners
  contact_phone    text,
  contact_email    text,
  updated_at       text
);

-- Ensure a single settings row exists so we always upsert into id=1
insert into company_settings (id, company_name) values (1, 'My Company')
  on conflict (id) do nothing;
